const assert = require('node:assert/strict');
const path = require('node:path');
const os = require('node:os');
require('node:fs').mkdirSync('outputs', { recursive: true });
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || path.join(os.homedir(), '.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));

(async () => {
  const browser = await chromium.launch({ headless: true, args: ['--autoplay-policy=document-user-activation-required'] });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
    page.setDefaultTimeout(10000);
    const errors = [];
    const audioRequests = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('request', request => { if (request.url().includes('/media/buon-vuong-mi.mp3')) audioRequests.push(request.url()); });
    await page.addInitScript(() => {
      window.__playCalls = [];
      const play = HTMLMediaElement.prototype.play;
      HTMLMediaElement.prototype.play = function () {
        window.__playCalls.push({ volume: this.volume, activation: navigator.userActivation.isActive, entry: document.querySelector('.tpp-root')?.dataset.entry });
        return play.call(this);
      };
    });
    const url = process.argv[2] || 'http://localhost:3001';
    await page.goto(url, { waitUntil: 'networkidle' });
    assert.match(await page.title(), /^Astraa/);
    assert.equal(await page.locator('.tpp-root h1').textContent(), 'A developer with aneye for the interface.');
    assert.doesNotMatch(await page.locator('.tpp-root').textContent(), /Kedhareswer|Hyderabad|Frostline|Hearth|Nordlys|7 years|40\+ launches|example\.com/);
    const audio = page.locator('.music-stamp audio');
    const music = page.getByRole('region', { name: 'Music player controls', exact: true });
    const musicTrigger = page.getByRole('button', { name: /^Music player/ });
    const enter = async target => {
      await target.getByRole('button', { name: 'Open letter', exact: true }).click();
      await target.locator('.tpp-root[data-entry=entered]').waitFor();
    };
    assert.equal(await page.locator('.tpp-track').evaluate(node => node.inert && getComputedStyle(node).visibility === 'hidden'), true);
    assert.equal(await page.getByRole('navigation', { name: 'Chapters' }).count(), 0, 'The sealed letter must hide the portfolio from accessibility navigation.');
    await page.mouse.wheel(0, 600);
    assert.equal(await page.evaluate(() => scrollY), 0, 'The sealed letter must lock background scrolling.');
    assert.deepEqual(audioRequests, [], 'The sealed letter must not download or start the soundtrack.');
    assert.deepEqual(await page.evaluate(() => window.__playCalls), []);
    assert.equal(await audio.evaluate(node => node.paused && !node.autoplay && node.loop), true);
    assert.equal(await audio.evaluate(node => node.volume), .35);
    assert.match(await page.locator('.tpp-entry-caption').textContent(), /^Click to open the letter/);
    await page.screenshot({ path: 'outputs/astraa-entry-sealed.png' });
    await page.getByRole('button', { name: 'Open letter', exact: true }).hover();
    await page.waitForTimeout(280);
    assert.match(await page.locator('.tpp-entry-envelope').evaluate(node => getComputedStyle(node).transform), /^matrix3d/);
    assert.notEqual(await page.locator('.tpp-entry-flap').evaluate(node => getComputedStyle(node).transform), 'none');
    assert.notEqual(await page.locator('.tpp-entry-letter').evaluate(node => getComputedStyle(node).transform), 'none');
    await page.screenshot({ path: 'outputs/astraa-entry-hover.png' });
    await page.getByRole('button', { name: 'Open letter', exact: true }).click();
    assert.equal(await page.locator('.tpp-root').getAttribute('data-entry'), 'opening');
    assert.equal(await page.locator('.tpp-track').evaluate(node => node.inert), true);
    assert.deepEqual(await page.evaluate(() => window.__playCalls), [{ volume: .35, activation: true, entry: 'sealed' }], 'Play must run synchronously inside the opening click at 35%.');
    await page.waitForTimeout(350);
    await page.screenshot({ path: 'outputs/astraa-entry-opening.png' });
    await page.locator('.tpp-root[data-entry=entered]').waitFor();
    assert.equal(await page.locator('.tpp-track').evaluate(node => node.inert), false);
    assert.equal(await page.getByRole('button', { name: 'Astraa', exact: true }).evaluate(node => node === document.activeElement), true);
    await page.waitForFunction(() => { const media = document.querySelector('.music-stamp audio'); return !media.paused && media.currentTime > .2; });
    await musicTrigger.click();
    const play = page.getByRole('button', { name: 'Play background music', exact: true });
    assert.equal(await page.getByRole('button', { name: 'Pause background music', exact: true }).evaluate(node => node === document.activeElement), true, 'Opening the player should focus the playback control.');
    const hud = await music.boundingBox();
    assert.ok(hud.width <= 250 && hud.height <= 170, 'The music HUD must stay compact.');
    assert.match(await music.getByRole('heading').evaluate(node => getComputedStyle(node).fontFamily), /system-ui/);
    assert.equal(await music.getByRole('heading').textContent(), 'Buồn vương mi');
    assert.ok(audioRequests.length > 0);
    assert.ok(await audio.evaluate(node => Number.isFinite(node.duration) && node.duration > 0));
    assert.equal(await audio.evaluate(node => node.volume), .35);
    await page.screenshot({ path: 'outputs/astraa-music-stamp.png' });
    const volume = page.getByRole('slider', { name: 'Music volume', exact: true });
    await volume.focus();
    await page.keyboard.press('ArrowLeft');
    assert.equal(await audio.evaluate(node => node.volume), .34);
    await page.getByRole('button', { name: 'Mute music', exact: true }).click();
    assert.equal(await audio.evaluate(node => node.muted), true);
    await page.getByRole('button', { name: 'Unmute music', exact: true }).click();
    assert.equal(await audio.evaluate(node => node.muted), false);
    assert.equal(await audio.evaluate(node => node.volume), .34);
    await page.getByRole('button', { name: 'Pause background music', exact: true }).click();
    const pausedAt = await audio.evaluate(node => node.currentTime);
    await page.waitForTimeout(300);
    assert.equal(await audio.evaluate(node => node.currentTime), pausedAt);
    await page.getByRole('slider', { name: 'Track position', exact: true }).focus();
    await page.keyboard.press('Home');
    for (let i = 0; i < 5; i++) await page.keyboard.press('ArrowRight');
    assert.ok(Math.abs(await audio.evaluate(node => node.currentTime) - .5) < .01, 'The keyboard must seek the real media.');
    await play.click();
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('.music-card').evaluate(node => node.matches(':popover-open')), false);
    assert.equal(await musicTrigger.evaluate(node => node === document.activeElement), true);
    const go = async label => {
      console.log('Checking chapter:', label);
      await page.getByRole('navigation', { name: 'Chapters' }).getByRole('button', { name: label, exact: true }).click();
      await page.waitForTimeout(1800);
      assert.equal(await page.locator('.tpp-link[aria-current=true]').textContent(), label);
    };
    await go('About');
    const aboutCopy = page.locator('.tpp-about-copy');
    assert.equal(await aboutCopy.evaluate(node => node.scrollHeight <= node.clientHeight + 1 && getComputedStyle(node).overflowY === 'visible'), true, 'About must fit the paper without nested scrolling or clipped copy.');
    assert.equal(await page.getByRole('img', { name: 'Astraa — portrait', exact: true }).getAttribute('src'), '/media/astraa-portrait.webp');
    assert.equal(await page.locator('link[rel=icon]').getAttribute('href'), '/media/avatar-personal.png');
    assert.equal(await page.locator('img[src="/media/avatar.png"]').count(), 0);
    const gallery = page.getByRole('button', { name: 'Next personal photo', exact: true });
    const personalPhotos = ['team', 'friends', 'working', 'workspace', 'team-session'];
    const gallerySize = await gallery.evaluate(node => [node.clientWidth, node.clientHeight]);
    assert.ok(await gallery.evaluate(node => node.parentElement.clientWidth / node.parentElement.parentElement.clientWidth > .55), 'The personal polaroid must be larger than the old 42% thumbnail.');
    await page.screenshot({ path: 'outputs/astraa-about-personal.png' });
    for (let i = 0; i < personalPhotos.length; i++) {
      assert.equal(await gallery.locator('img[data-current]').getAttribute('src'), '/media/' + personalPhotos[i] + '.webp');
      assert.deepEqual(await gallery.evaluate(node => [node.clientWidth, node.clientHeight]), gallerySize, 'Every photo must use the same gallery frame.');
      await gallery.click();
    }
    assert.equal(await gallery.locator('img[data-current]').getAttribute('src'), '/media/team.webp', 'The gallery must wrap back to the team photo.');
    await gallery.focus();
    await page.keyboard.press('ArrowLeft');
    assert.equal(await gallery.locator('img[data-current]').getAttribute('src'), '/media/team-session.webp');
    assert.equal(await gallery.getAttribute('data-animate'), null, 'Keyboard navigation must swap instantly.');
    await page.keyboard.press('ArrowRight');
    await page.keyboard.press('Enter');
    assert.equal(await gallery.locator('img[data-current]').getAttribute('src'), '/media/friends.webp');
    assert.match(await gallery.locator('[aria-live=polite]').textContent(), /Photo 2 of 5/);
    await page.screenshot({ path: 'outputs/astraa-about-gallery.png' });
    await page.screenshot({ path: 'outputs/astraa-about-no-scrollbar.png' });
    assert.equal(await audio.evaluate(node => node.paused), false, 'Music must continue between chapters.');
    await musicTrigger.click();
    await page.getByRole('button', { name: 'Pause background music', exact: true }).click();
    await page.getByRole('button', { name: 'Close music player', exact: true }).click();
    await page.getByRole('button', { name: 'Turn over ↻', exact: true }).click();
    await page.waitForTimeout(700);
    assert.equal(await page.locator('.tpp-flip').getAttribute('data-back'), '');
    assert.equal(await page.locator('[data-side=front]').evaluate(node => node.inert), true);
    assert.match(await page.locator(':focus').textContent(), /Front/);
    assert.match(await page.getByRole('region', { name: 'About', exact: true }).innerText(), /Ho Chi Minh, Vietnam/);
    assert.equal(await page.locator('a[href="mailto:lagna0175@gmail.com"]').count(), 1);
    await go('Work');
    assert.equal(await audio.evaluate(node => node.paused), true, 'A manual Pause must survive later site interactions.');
    const names = ['ProZ0', 'MediMate AI', 'FinGenie', 'GeoConnect', 'CVmate', 'Ecommerce Mobile', 'MLN Web'];
    const paths = ['ProZ0', 'SEP490_FE_MedicalAIAssistant', 'FinGenie', 'geoconnect', 'CVmate', 'ecomerce-mobile', 'MLN-web'];
    assert.equal(await page.locator('.tpp-polaroid img').count(), 7, 'Every project must have an actual preview instead of a generated landscape.');
    const note = page.locator('.tpp-hero-note');
    await go('Cover');
    await page.mouse.move(1200, 700);
    await note.hover();
    await page.waitForFunction(() => Math.abs(parseFloat(getComputedStyle(document.querySelector('.tpp-hero-note')).translate.split(' ')[1]) + 3) < .05);
    assert.ok(await note.evaluate(node => Math.abs(parseFloat(getComputedStyle(node).translate.split(' ')[1]) + 3) < .05), 'Paper hover must work alongside its inline rotation.');
    await go('Work');
    for (let i = 0; i < names.length; i++) {
      assert.equal(await page.getByRole('group', { name: 'Projects', exact: true }).locator('[aria-current=true]').getAttribute('aria-label'), names[i]);
      assert.equal(await page.getByRole('link', { name: 'View project ↗', exact: true }).getAttribute('href'), 'https://github.com/5erax/' + paths[i]);
      if (i === 0) await page.screenshot({ path: 'outputs/astraa-scroll-work-preview.png' });
      await page.getByRole('button', { name: 'Next project', exact: true }).click();
      await page.waitForTimeout(450);
    }
    assert.equal(await page.getByRole('group', { name: 'Projects', exact: true }).locator('[aria-current=true]').getAttribute('aria-label'), 'ProZ0');
    await page.getByRole('button', { name: 'Next project', exact: true }).focus();
    const workY = await page.evaluate(() => scrollY);
    await page.keyboard.press('ArrowLeft');
    assert.equal(await page.getByRole('group', { name: 'Projects', exact: true }).locator('[aria-current=true]').getAttribute('aria-label'), 'MLN Web');
    assert.equal(await page.evaluate(() => scrollY), workY);
    for (let i = 0; i < 5; i++) await page.getByRole('button', { name: 'Next project', exact: true }).click();
    await page.waitForTimeout(500);
    assert.equal(await page.getByRole('group', { name: 'Projects', exact: true }).locator('[aria-current=true]').getAttribute('aria-label'), 'CVmate');
    await go('Journey');
    const pin = page.locator('.tpp-pin').first();
    await pin.click();
    assert.equal(await pin.getAttribute('aria-pressed'), 'true');
    await go('Contact');
    await page.getByRole('button', { name: 'Open email draft ↗', exact: true }).click();
    assert.equal(await page.locator('textarea').evaluate(node => node === document.activeElement), true);
    assert.equal(await page.locator('textarea').getAttribute('aria-invalid'), 'true');
    assert.match(await page.getByRole('status').innerText(), /Write a short message/);
    await page.locator('textarea').fill('A small test draft.');
    assert.equal(await page.locator('textarea').getAttribute('aria-invalid'), 'false');
    await page.getByRole('textbox', { name: 'From', exact: true }).fill('invalid-address');
    assert.equal(await page.getByRole('textbox', { name: 'From', exact: true }).evaluate(node => node.validity.typeMismatch), true);
    // Exercise clipboard rejection without sending an email or opening an external app.
    await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: () => Promise.reject(new Error('denied')) } }));
    await page.getByRole('button', { name: 'Copy email', exact: true }).click();
    assert.match(await page.getByRole('status').innerText(), /Copy unavailable/);
    assert.equal(await page.getByRole('link', { name: 'GitHub', exact: true }).getAttribute('href'), 'https://github.com/5erax');
    assert.equal(await page.getByRole('link', { name: 'LinkedIn', exact: true }).count(), 0);
    const unavailableLinkedIn = page.getByRole('button', { name: 'LinkedIn — temporarily unavailable', exact: true });
    assert.equal(await unavailableLinkedIn.isDisabled(), true);
    const currentUrl = page.url();
    const openPages = page.context().pages().length;
    await unavailableLinkedIn.click({ force: true });
    assert.equal(page.url(), currentUrl);
    assert.equal(page.context().pages().length, openPages, 'The unavailable LinkedIn tag must not open another tab.');
    await go('Cover');
    await page.screenshot({ path: 'outputs/astraa-scroll-cover-preview.png' });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await page.mouse.wheel(0, 780);
    await page.locator('.tpp-root[data-scrolling]').waitFor();
    assert.ok(await page.locator('.tpp-ch[data-on] .tpp-flake').evaluateAll(nodes => nodes.length > 0 && nodes.every(node => getComputedStyle(node).animationPlayState === 'paused')), 'Ambient snow must pause while paper follows the wheel.');
    await page.waitForFunction(() => [...document.querySelectorAll('.tpp-ch[data-on] .tpp-light')].some(node => +node.style.opacity > .01));
    assert.ok(await page.locator('.tpp-ch[data-on] .tpp-light').evaluateAll(nodes => nodes.some(node => +node.style.opacity > .01)), 'Tearing paper should react to scroll with directional light.');
    assert.match(await page.locator('.tpp-ch[data-on] .tpp-up').first().getAttribute('style'), /rotateX/);
    await page.screenshot({ path: 'outputs/astraa-scroll-tear.png' });
    const restY = await page.evaluate(() => scrollY);
    await page.waitForTimeout(700);
    assert.equal(await page.evaluate(() => scrollY), restY, 'A resting wheel gesture must not trigger an unsolicited chapter snap.');
    await page.locator('.tpp-root[data-scrolling]').waitFor({ state: 'hidden' });
    assert.ok(await page.locator('.tpp-ch[data-on] .tpp-flake').evaluateAll(nodes => nodes.length > 0 && nodes.every(node => getComputedStyle(node).animationPlayState === 'running')), 'Ambient motion must resume once the paper settles.');
    await go('Cover');
    await page.setViewportSize({ width: 390, height: 844 });
    await page.reload({ waitUntil: 'networkidle' });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    assert.equal(await audio.evaluate(node => node.paused), true, 'A fresh document must wait for its envelope.');
    await page.screenshot({ path: 'outputs/astraa-entry-mobile.png' });
    const entryTouch = await page.context().newCDPSession(page);
    const envelope = await page.getByRole('button', { name: 'Open letter', exact: true }).boundingBox();
    await entryTouch.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: envelope.x + envelope.width / 2, y: envelope.y + envelope.height / 2 }] });
    await entryTouch.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
    await page.locator('.tpp-root[data-entry=entered]').waitFor();
    await page.waitForFunction(() => document.querySelector('audio').currentTime > .1);
    await musicTrigger.click();
    await page.screenshot({ path: 'outputs/astraa-music-mobile.png' });
    assert.equal(await music.evaluate(node => node.scrollWidth > node.clientWidth), false);
    await page.keyboard.press('Escape');
    const mobileGo = async label => {
      await page.getByRole('button', { name: 'Choose chapter', exact: true }).click();
      await page.getByRole('navigation', { name: 'Chapter index', exact: true }).getByRole('button', { name: label + ' ', exact: false }).click();
      await page.waitForTimeout(1500);
      assert.equal(await page.locator('.tpp-index').evaluate(node => node.matches(':popover-open')), false);
    };
    await page.getByRole('button', { name: 'Choose chapter', exact: true }).click();
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('.tpp-index').evaluate(node => node.matches(':popover-open')), false);
    await page.getByRole('button', { name: 'Choose chapter', exact: true }).click();
    await page.mouse.click(10, 740);
    assert.equal(await page.locator('.tpp-index').evaluate(node => node.matches(':popover-open')), false);
    await mobileGo('About');
    assert.equal(await aboutCopy.evaluate(node => node.scrollHeight <= node.clientHeight + 1 && getComputedStyle(node).overflowY === 'visible'), true);
    const touchGalleryBox = await gallery.boundingBox();
    assert.ok(touchGalleryBox.x >= 0 && touchGalleryBox.x + touchGalleryBox.width <= 390);
    await entryTouch.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: touchGalleryBox.x + touchGalleryBox.width / 2, y: touchGalleryBox.y + touchGalleryBox.height / 2 }] });
    await entryTouch.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
    assert.equal(await gallery.locator('img[data-current]').getAttribute('src'), '/media/friends.webp', 'Touch must advance the mini gallery.');
    await page.waitForFunction(() => getComputedStyle(document.querySelector('.tpp-mini-gallery img[data-current]')).opacity === '1');
    await page.screenshot({ path: 'outputs/astraa-scroll-mobile-preview.png' });
    await mobileGo('Work');
    const deck = page.locator('.tpp-project-stack');
    const box = await deck.boundingBox();
    await page.mouse.move(box.x + box.width * .8, box.y + box.height * .5);
    await page.mouse.down();
    await page.mouse.move(box.x + box.width * .2, box.y + box.height * .5, { steps: 8 });
    await page.mouse.up();
    assert.equal(await page.getByRole('group', { name: 'Projects', exact: true }).locator('[aria-current=true]').getAttribute('aria-label'), 'MediMate AI');
    const touch = await page.context().newCDPSession(page);
    const swipe = async (x1, y1, x2, y2) => {
      await touch.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: x1, y: y1 }] });
      for (let i = 1; i <= 8; i++) {
        await touch.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x1 + (x2 - x1) * i / 8, y: y1 + (y2 - y1) * i / 8 }] });
        await page.waitForTimeout(20);
      }
      await touch.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
      await page.waitForTimeout(500);
    };
    await swipe(box.x + box.width * .2, box.y + box.height * .5, box.x + box.width * .8, box.y + box.height * .5);
    assert.equal(await page.getByRole('group', { name: 'Projects', exact: true }).locator('[aria-current=true]').getAttribute('aria-label'), 'ProZ0');
    const panY = await page.evaluate(() => scrollY);
    await swipe(box.x + box.width * .5, box.y + box.height * .8, box.x + box.width * .5, box.y + box.height * .2);
    assert.ok(await page.evaluate(() => scrollY) > panY + 20, 'Vertical touch gestures must keep native page scrolling.');
    await page.waitForTimeout(500);
    await page.screenshot({ path: 'outputs/astraa-scroll-mobile-work.png' });
    await page.setViewportSize({ width: 390, height: 640 });
    await page.waitForTimeout(400);
    assert.equal(await page.locator('.tpp-root').getAttribute('data-mode'), 'stack');
    assert.match(await page.getByRole('button', { name: 'Choose chapter', exact: true }).textContent(), /03/);
    await page.setViewportSize({ width: 390, height: 844 });
    await page.waitForTimeout(500);
    assert.equal(await page.locator('.tpp-root').getAttribute('data-mode'), 'pin');
    assert.match(await page.getByRole('button', { name: 'Choose chapter', exact: true }).textContent(), /03/);
    assert.equal(await page.locator('img').evaluateAll(images => images.filter(image => image.src && !image.complete || image.src && image.naturalWidth === 0).length), 0);
    await page.emulateMedia({ reducedMotion: 'reduce' });
    await page.waitForTimeout(300);
    assert.equal(await page.locator('.music-record').evaluate(node => getComputedStyle(node).animationName), 'none');
    assert.match(await page.getByRole('button', { name: 'Choose chapter', exact: true }).textContent(), /03/);
    await page.reload({ waitUntil: 'networkidle' });
    await page.getByRole('button', { name: 'Open letter', exact: true }).focus();
    await page.keyboard.press('Enter');
    assert.equal(await page.locator('.tpp-root').getAttribute('data-entry'), 'entered', 'Reduced motion and keyboard entry must reveal without waiting for animation.');
    assert.equal(await page.locator('.tpp-root').getAttribute('data-mode'), 'stack');
    assert.equal(await page.locator('.tpp-ch').count(), 5);
    await page.getByRole('button', { name: 'Choose chapter', exact: true }).click();
    await page.getByRole('navigation', { name: 'Chapter index', exact: true }).getByRole('button', { name: /Contact/ }).click();
    await page.waitForTimeout(300);
    assert.match(await page.getByRole('button', { name: 'Choose chapter', exact: true }).textContent(), /05/);
    for (const [width, height] of [[320, 640], [768, 1024], [1024, 768]]) {
      await page.emulateMedia({ reducedMotion: 'no-preference' });
      await page.setViewportSize({ width, height });
      await page.goto(url, { waitUntil: 'networkidle' });
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
      await enter(page);
      if (width === 320) {
        assert.equal(await page.locator('.tpp-root').getAttribute('data-mode'), 'stack');
        await musicTrigger.click();
        const musicBox = await music.boundingBox();
        assert.ok(musicBox.x >= 0 && musicBox.x + musicBox.width <= width && musicBox.y + musicBox.height < height && musicBox.height <= 170, 'The compact music card must fit a small screen.');
        await page.screenshot({ path: 'outputs/astraa-music-small.png' });
        await page.keyboard.press('Escape');
        await mobileGo('About');
        assert.equal(await aboutCopy.evaluate(node => node.scrollHeight <= node.clientHeight + 1), true, 'The complete About note must fit even at 320px.');
        const smallGallery = await gallery.boundingBox();
        assert.ok(smallGallery.width >= 120 && smallGallery.x >= 0 && smallGallery.x + smallGallery.width <= width, 'The personal gallery must remain readable and inside the narrow postcard.');
        await mobileGo('Contact');
        const submit = await page.getByRole('button', { name: 'Open email draft ↗', exact: true }).boundingBox();
        assert.ok(submit.y >= 0 && submit.y + submit.height <= height, 'Small-screen contact action must fit the viewport.');
        await page.screenshot({ path: 'outputs/astraa-scroll-small-contact.png' });
      }
    }
    const failedMedia = await browser.newPage();
    failedMedia.on('pageerror', error => errors.push(error.message));
    await failedMedia.route('**/media/buon-vuong-mi.mp3', route => route.fulfill({ status: 503, body: 'Unavailable' }));
    await failedMedia.goto(url, { waitUntil: 'networkidle' });
    await enter(failedMedia);
    await failedMedia.getByRole('button', { name: 'Music player', exact: true }).click();
    await failedMedia.waitForFunction(() => /unavailable|Couldn’t play/.test(document.querySelector('.music-status').textContent));
    assert.equal(await failedMedia.locator('audio').evaluate(node => node.paused), true);
    await failedMedia.unroute('**/media/buon-vuong-mi.mp3');
    await failedMedia.getByRole('button', { name: 'Play background music', exact: true }).click();
    await failedMedia.waitForFunction(() => !document.querySelector('audio').paused && document.querySelector('audio').currentTime > .1);
    await failedMedia.getByRole('button', { name: 'Pause background music', exact: true }).click();
    await failedMedia.evaluate(() => { HTMLMediaElement.prototype.play = () => Promise.reject(new DOMException('Blocked', 'NotAllowedError')); });
    await failedMedia.getByRole('button', { name: 'Play background music', exact: true }).click();
    assert.match(await failedMedia.locator('.music-status').textContent(), /Couldn’t play/);
    await failedMedia.close();
    const deviceVolume = await browser.newPage();
    await deviceVolume.addInitScript(() => Object.defineProperty(HTMLMediaElement.prototype, 'volume', { configurable: true, get: () => 1, set: () => {} }));
    await deviceVolume.goto(url, { waitUntil: 'networkidle' });
    await enter(deviceVolume);
    await deviceVolume.getByRole('button', { name: /^Music player/ }).click();
    assert.equal(await deviceVolume.getByRole('slider', { name: 'Music volume', exact: true }).count(), 0, 'A read-only volume API must use the device controls.');
    assert.equal(await deviceVolume.getByText('Use your device volume', { exact: true }).isVisible(), true);
    await deviceVolume.close();
    // Exercise the other real browser policy: autoplay permitted without a gesture.
    const allowedBrowser = await chromium.launch({ headless: true, args: ['--autoplay-policy=no-user-gesture-required'] });
    try {
      const allowed = await allowedBrowser.newPage();
      allowed.on('pageerror', error => errors.push(error.message));
      await allowed.addInitScript(() => {
        window.__initialPlayVolume = [];
        document.addEventListener('play', event => { if (event.target instanceof HTMLAudioElement) window.__initialPlayVolume.push(event.target.volume); }, true);
      });
      await allowed.goto(url, { waitUntil: 'networkidle' });
      assert.equal(await allowed.locator('audio').evaluate(node => node.paused && node.currentTime === 0), true, 'Even permissive browsers must wait for the envelope.');
      await allowed.getByRole('button', { name: 'Open letter', exact: true }).focus();
      await allowed.keyboard.press('Space');
      await allowed.locator('.tpp-root[data-entry=entered]').waitFor();
      await allowed.waitForFunction(() => document.querySelector('audio').currentTime > .2);
      assert.equal(await allowed.locator('audio').evaluate(node => node.volume), .35);
      assert.deepEqual(await allowed.evaluate(() => window.__initialPlayVolume), [.35], 'Envelope entry must set volume before the first sound.');
      await allowed.getByRole('button', { name: 'Music player — playing', exact: true }).click();
      await allowed.getByRole('button', { name: 'Pause background music', exact: true }).click();
      await allowed.keyboard.press('Escape');
      await allowed.getByRole('button', { name: 'Astraa', exact: true }).click();
      assert.equal(await allowed.locator('audio').evaluate(node => node.paused), true);
    } finally { await allowedBrowser.close(); }
    assert.deepEqual(errors, []);
    console.log('PASS: personal portrait/avatar, fixed-frame mini gallery with team + four photos, click/touch/keyboard/wrap/live announcements, disabled LinkedIn without navigation, letter entry and 35% music, About/scroll/ambient behavior, seven project images, audio/error/device-volume controls, portfolio flows, 320–1440px layouts, no browser errors.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
